resources:
  - nginx-deployment.yml
  - nginx-image-policy.yml
  - nginx-repo.yml
  - nginx-manifest-update.yml
  - nginx-hpa.yml
  - nginx-service.yml
  - nginx-ingress.yml
  - nginx-image-reflect-sa.yml

