apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-texsite
  namespace: monitoring
  labels:
    release: monitoring-prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: nginx-texsite
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
