apiVersion: v1
kind: Service
metadata:
  name: nginx-texsite
  namespace: default
spec:
  selector:
    app: nginx-texsite
  ports:
    - port: 80
      targetPort: 80
    - port: 8080
      targetPort: 8080
  type: ClusterIP
